/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wdqapi_WdqApi */

#ifndef _Included_wdqapi_WdqApi
#define _Included_wdqapi_WdqApi
#ifdef __cplusplus
extern "C" {
#endif
#undef wdqapi_WdqApi_WDQ_NUM_WEP_KEYS_MAX
#define wdqapi_WdqApi_WDQ_NUM_WEP_KEYS_MAX 4L
#undef wdqapi_WdqApi_WDQ_WEP_KEY_SIZE
#define wdqapi_WdqApi_WDQ_WEP_KEY_SIZE 13L
#undef wdqapi_WdqApi_WDQ_MAC_ADDR_SIZE
#define wdqapi_WdqApi_WDQ_MAC_ADDR_SIZE 6L
#undef wdqapi_WdqApi_WDQ_MAX_NUM_NETWORKS
#define wdqapi_WdqApi_WDQ_MAX_NUM_NETWORKS 16L
#undef wdqapi_WdqApi_WDQ_MAX_SSID_SIZE
#define wdqapi_WdqApi_WDQ_MAX_SSID_SIZE 32L
#undef wdqapi_WdqApi_WDQ_MAX_NAME_SIZE
#define wdqapi_WdqApi_WDQ_MAX_NAME_SIZE 20L
#undef wdqapi_WdqApi_WDQ_MAX_PASSWORD_SIZE
#define wdqapi_WdqApi_WDQ_MAX_PASSWORD_SIZE 64L
#undef wdqapi_WdqApi_WDQ_MAX_PROBE_AP
#define wdqapi_WdqApi_WDQ_MAX_PROBE_AP 64L
#undef wdqapi_WdqApi_WDQ_MAX_PATH
#define wdqapi_WdqApi_WDQ_MAX_PATH 260L
#undef wdqapi_WdqApi_WDQ_APIERR_SUCCESS
#define wdqapi_WdqApi_WDQ_APIERR_SUCCESS 0L
#undef wdqapi_WdqApi_WDQ_APIERR_NULLPTR
#define wdqapi_WdqApi_WDQ_APIERR_NULLPTR -1L
#undef wdqapi_WdqApi_WDQ_APIERR_BADARG
#define wdqapi_WdqApi_WDQ_APIERR_BADARG -2L
#undef wdqapi_WdqApi_WDQ_APIERR_BADSIZE
#define wdqapi_WdqApi_WDQ_APIERR_BADSIZE -3L
#undef wdqapi_WdqApi_WDQ_APIERR_GENERAL
#define wdqapi_WdqApi_WDQ_APIERR_GENERAL -4L
#undef wdqapi_WdqApi_WDQ_APIERR_MEMORY
#define wdqapi_WdqApi_WDQ_APIERR_MEMORY -5L
#undef wdqapi_WdqApi_WDQ_APIERR_BADWRITE
#define wdqapi_WdqApi_WDQ_APIERR_BADWRITE -6L
#undef wdqapi_WdqApi_WDQ_APIERR_BADREAD
#define wdqapi_WdqApi_WDQ_APIERR_BADREAD -7L
#undef wdqapi_WdqApi_WDQ_APIERR_NOTFOUND
#define wdqapi_WdqApi_WDQ_APIERR_NOTFOUND -8L
#undef wdqapi_WdqApi_WDQ_APIERR_BADOPEN
#define wdqapi_WdqApi_WDQ_APIERR_BADOPEN -9L
#undef wdqapi_WdqApi_WDQ_APIERR_COLLISION
#define wdqapi_WdqApi_WDQ_APIERR_COLLISION -10L
#undef wdqapi_WdqApi_WDQ_APIERR_BADCREATE
#define wdqapi_WdqApi_WDQ_APIERR_BADCREATE -11L
#undef wdqapi_WdqApi_WDQ_APIERR_CFGLOCKED
#define wdqapi_WdqApi_WDQ_APIERR_CFGLOCKED -12L
#undef wdqapi_WdqApi_WDQ_APIERR_MOREDATA
#define wdqapi_WdqApi_WDQ_APIERR_MOREDATA -13L
/*
 * Class:     wdqapi_WdqApi
 * Method:    NativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wdqapi_WdqApi_NativeInit
  (JNIEnv *, jclass);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqGetVersion
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqGetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqStartScan
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqStartScan
  (JNIEnv *, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqEnableAutoNetworkSwitch
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqEnableAutoNetworkSwitch
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqSetCurrentNetwork
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqSetCurrentNetwork
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqSetCertPath
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqSetCertPath
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqSetRadioParameters
 * Signature: (Lwdqapi/WdqApi/radioStore_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqSetRadioParameters
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqGetNetwork
 * Signature: (Ljava/lang/String;Lwdqapi/WdqApi/netStoreElem_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqGetNetwork
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqAddNetwork
 * Signature: (Lwdqapi/WdqApi/netStoreElem_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqAddNetwork
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqChangeNetwork
 * Signature: (Ljava/lang/String;Lwdqapi/WdqApi/netStoreElem_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqChangeNetwork
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqDeleteNetwork
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqDeleteNetwork
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqGetConfiguration
 * Signature: (Lwdqapi/WdqApi/radioData_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqGetConfiguration
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqGetStatus
 * Signature: (Lwdqapi/WdqApi/status_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqGetStatus
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqGetScanList
 * Signature: (Lwdqapi/WdqApi/scanList_t;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqGetScanList
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqSetDbgOut
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_wdqapi_WdqApi_WdqSetDbgOut
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqStartPingTest
 * Signature: (Ljava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_wdqapi_WdqApi_WdqStartPingTest
  (JNIEnv *, jobject, jstring, jint, jstring, jint);

/*
 * Class:     wdqapi_WdqApi
 * Method:    WdqStopPingTest
 * Signature: (I)I
 */
JNIEXPORT void JNICALL Java_wdqapi_WdqApi_WdqStopPingTest
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_scanList_t */

#ifndef _Included_wdqapi_WdqApi_scanList_t
#define _Included_wdqapi_WdqApi_scanList_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_scanElement_t */

#ifndef _Included_wdqapi_WdqApi_scanElement_t
#define _Included_wdqapi_WdqApi_scanElement_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_status_t */

#ifndef _Included_wdqapi_WdqApi_status_t
#define _Included_wdqapi_WdqApi_status_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_SSID_t */

#ifndef _Included_wdqapi_WdqApi_SSID_t
#define _Included_wdqapi_WdqApi_SSID_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_radioData_t */

#ifndef _Included_wdqapi_WdqApi_radioData_t
#define _Included_wdqapi_WdqApi_radioData_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_radioSpecificStore_t */

#ifndef _Included_wdqapi_WdqApi_radioSpecificStore_t
#define _Included_wdqapi_WdqApi_radioSpecificStore_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_radioStore_t */

#ifndef _Included_wdqapi_WdqApi_radioStore_t
#define _Included_wdqapi_WdqApi_radioStore_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_networkStore_t */

#ifndef _Included_wdqapi_WdqApi_networkStore_t
#define _Included_wdqapi_WdqApi_networkStore_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_netStoreElem_t */

#ifndef _Included_wdqapi_WdqApi_netStoreElem_t
#define _Included_wdqapi_WdqApi_netStoreElem_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_pingResults_t */

#ifndef _Included_wdqapi_WdqApi_pingResults_t
#define _Included_wdqapi_WdqApi_pingResults_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_pingResultsStatus_e */

#ifndef _Included_wdqapi_WdqApi_pingResultsStatus_e
#define _Included_wdqapi_WdqApi_pingResultsStatus_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_Version */

#ifndef _Included_wdqapi_WdqApi_Version
#define _Included_wdqapi_WdqApi_Version
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_scanElemOpts_e */

#ifndef _Included_wdqapi_WdqApi_scanElemOpts_e
#define _Included_wdqapi_WdqApi_scanElemOpts_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_apiFlags_e */

#ifndef _Included_wdqapi_WdqApi_apiFlags_e
#define _Included_wdqapi_WdqApi_apiFlags_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_testModes_e */

#ifndef _Included_wdqapi_WdqApi_testModes_e
#define _Included_wdqapi_WdqApi_testModes_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_debugType_e */

#ifndef _Included_wdqapi_WdqApi_debugType_e
#define _Included_wdqapi_WdqApi_debugType_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_connStatus_e */

#ifndef _Included_wdqapi_WdqApi_connStatus_e
#define _Included_wdqapi_WdqApi_connStatus_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_radioType_e */

#ifndef _Included_wdqapi_WdqApi_radioType_e
#define _Included_wdqapi_WdqApi_radioType_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_authHint_e */

#ifndef _Included_wdqapi_WdqApi_authHint_e
#define _Included_wdqapi_WdqApi_authHint_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_eapOpts_e */

#ifndef _Included_wdqapi_WdqApi_eapOpts_e
#define _Included_wdqapi_WdqApi_eapOpts_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_eapType_e */

#ifndef _Included_wdqapi_WdqApi_eapType_e
#define _Included_wdqapi_WdqApi_eapType_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_wpaType_e */

#ifndef _Included_wdqapi_WdqApi_wpaType_e
#define _Included_wdqapi_WdqApi_wpaType_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_passwordType_e */

#ifndef _Included_wdqapi_WdqApi_passwordType_e
#define _Included_wdqapi_WdqApi_passwordType_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_authType80211_e */

#ifndef _Included_wdqapi_WdqApi_authType80211_e
#define _Included_wdqapi_WdqApi_authType80211_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_pmkCacheType_e */

#ifndef _Included_wdqapi_WdqApi_pmkCacheType_e
#define _Included_wdqapi_WdqApi_pmkCacheType_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_netElemOpts_e */

#ifndef _Included_wdqapi_WdqApi_netElemOpts_e
#define _Included_wdqapi_WdqApi_netElemOpts_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_antennaSelect_e */

#ifndef _Included_wdqapi_WdqApi_antennaSelect_e
#define _Included_wdqapi_WdqApi_antennaSelect_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_regDomain_e */

#ifndef _Included_wdqapi_WdqApi_regDomain_e
#define _Included_wdqapi_WdqApi_regDomain_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_dfsChanMode_e */

#ifndef _Included_wdqapi_WdqApi_dfsChanMode_e
#define _Included_wdqapi_WdqApi_dfsChanMode_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_radioOption_e */

#ifndef _Included_wdqapi_WdqApi_radioOption_e
#define _Included_wdqapi_WdqApi_radioOption_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_bandSelect_e */

#ifndef _Included_wdqapi_WdqApi_bandSelect_e
#define _Included_wdqapi_WdqApi_bandSelect_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class wdqapi_WdqApi_powerSaveMode_e */

#ifndef _Included_wdqapi_WdqApi_powerSaveMode_e
#define _Included_wdqapi_WdqApi_powerSaveMode_e
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
